modLoader="javafml"
loaderVersion="[44,)"
license="MIT License"
issueTrackerURL="https://github.com/toadie-odie/piglinmerchantmod/issues"
[[mods]]
modId="piglinmerchantmod"
version="1.19.3-0.0.1"
displayName="Piglin Merchant Mod"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/toadie-odie/piglinmerchantmod"
#logoFile="logo.png"
credits='''Special thanks to my sons, and my supporters:
Marshal Nash and Trevor Brannigan,
for supporting my blog and my various projects!'''
authors="Warren Tode (ToadieOdie)"
description="This mod adds the Piglin Merchant."

[[dependencies.piglinmerchantmod]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.piglinmerchantmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.piglinmerchantmod]]
modId="smartbrainlib"
mandatory=true
versionRange="[1.9,)"
ordering="NONE"
side="SERVER"

[[dependencies.piglinmerchantmod]]
modId="geckolib"
mandatory=true
versionRange="[4.0.6,)"
ordering="NONE"
side="SERVER"

[modproperties.piglinmerchantmod]
catalogueItemIcon="minecraft:textures/block/gold_ingot.png" #Support for Catalogue mod
configuredBackground="minecraft:textures/block/netherrack.png" #Support for Configured mod